/* Generated By:JJTree: Do not edit this line. ASTAllComparisonExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTAllComparisonExpression extends SimpleNode {
  public ASTAllComparisonExpression(int id) {
    super(id);
  }

  public ASTAllComparisonExpression(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=43563d79f10f80aef4165bceda152e34 (do not edit this line) */
