/* Generated By:JJTree: Do not edit this line. ASTAnyComparisonExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTAnyComparisonExpression extends SimpleNode {
  public ASTAnyComparisonExpression(int id) {
    super(id);
  }

  public ASTAnyComparisonExpression(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=deb5265d61093fe8e88eba1db9ea0987 (do not edit this line) */
