/* Generated By:JJTree: Do not edit this line. ASTAllTableCol.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTAllTableCol extends SimpleNode {
  public ASTAllTableCol(int id) {
    super(id);
  }

  public ASTAllTableCol(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ecb450a9fe93dd3dca04d0bb2e8bc5b2 (do not edit this line) */
