/* Generated By:JJTree: Do not edit this line. ASTAllTableColumns.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTAllTableColumns extends SimpleNode {
  public ASTAllTableColumns(int id) {
    super(id);
  }

  public ASTAllTableColumns(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6ccbe1fa30c0284b7e41795cef84591d (do not edit this line) */
