/* Generated By:JJTree: Do not edit this line. ASTColumnIndex.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTColumnIndex extends SimpleNode {
  public ASTColumnIndex(int id) {
    super(id);
  }

  public ASTColumnIndex(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f0dc4b889f44664dd0b48d6e83b771dd (do not edit this line) */
