/* Generated By:JJTree: Do not edit this line. ASTColumnsNamesList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTColumnsNamesList extends SimpleNode {
  public ASTColumnsNamesList(int id) {
    super(id);
  }

  public ASTColumnsNamesList(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8fba505e5e434d470bf5e8fa3dcefa11 (do not edit this line) */
