/* Generated By:JJTree: Do not edit this line. ASTDouble.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTDouble extends SimpleNode {
  public ASTDouble(int id) {
    super(id);
  }

  public ASTDouble(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5a85c4bd4e5c3ae4186a3a6eac59e8b0 (do not edit this line) */
