/* Generated By:JJTree: Do not edit this line. ASTFromItemsList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTFromItemsList extends SimpleNode {
  public ASTFromItemsList(int id) {
    super(id);
  }

  public ASTFromItemsList(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=010fc6df6b8a5dbefb02b0f195af31ab (do not edit this line) */
