/* Generated By:JJTree: Do not edit this line. ASTGroupByColumnReferences.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTGroupByColumnReferences extends SimpleNode {
  public ASTGroupByColumnReferences(int id) {
    super(id);
  }

  public ASTGroupByColumnReferences(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bfe35c962b81a049428c7e4abf86917b (do not edit this line) */
