/* Generated By:JJTree: Do not edit this line. ASTInverseExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTInverseExpression extends SimpleNode {
  public ASTInverseExpression(int id) {
    super(id);
  }

  public ASTInverseExpression(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b86e79e694db379bdbb0c77ff2fe0e07 (do not edit this line) */
