/* Generated By:JJTree: Do not edit this line. ASTJoinsList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTJoinsList extends SimpleNode {
  public ASTJoinsList(int id) {
    super(id);
  }

  public ASTJoinsList(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=14c4167abead45c6ab73c3e94887e3a1 (do not edit this line) */
