/* Generated By:JJTree: Do not edit this line. ASTJdbcParameter.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTJdbcParameter extends SimpleNode {
  public ASTJdbcParameter(int id) {
    super(id);
  }

  public ASTJdbcParameter(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8251d46a57b6236476dfbf4fe1961fb2 (do not edit this line) */
