/* Generated By:JJTree: Do not edit this line. ASTNull.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTNull extends SimpleNode {
  public ASTNull(int id) {
    super(id);
  }

  public ASTNull(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a5a6d57fe76471ee3e399a87f066e270 (do not edit this line) */
