/* Generated By:JJTree: Do not edit this line. ASTOrderByElements.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTOrderByElements extends SimpleNode {
  public ASTOrderByElements(int id) {
    super(id);
  }

  public ASTOrderByElements(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=af041fc5790d03ba5d3286129d899aec (do not edit this line) */
