/* Generated By:JJTree: Do not edit this line. ASTSQLExpressionList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTSQLExpressionList extends SimpleNode {
  public ASTSQLExpressionList(int id) {
    super(id);
  }

  public ASTSQLExpressionList(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=78b8673267de90917d46a6a0def1763a (do not edit this line) */
