/* Generated By:JJTree: Do not edit this line. ASTSimpleExpressionList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTSimpleExpressionList extends SimpleNode {
  public ASTSimpleExpressionList(int id) {
    super(id);
  }

  public ASTSimpleExpressionList(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b96e31fd170df8ad809ac55df1c4b77d (do not edit this line) */
