/* Generated By:JJTree: Do not edit this line. ASTSubSelect.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTSubSelect extends SimpleNode {
  public ASTSubSelect(int id) {
    super(id);
  }

  public ASTSubSelect(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=73850b8ff72d1c8bbdbdd13b4a60badb (do not edit this line) */
