/* Generated By:JJTree: Do not edit this line. ASTTableWithAlias.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTTableWithAlias extends SimpleNode {
  public ASTTableWithAlias(int id) {
    super(id);
  }

  public ASTTableWithAlias(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=38e71858f39382d1fc00121162aff3f2 (do not edit this line) */
