/* Generated By:JJTree: Do not edit this line. ASTWhenThenSearchCondition.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTWhenThenSearchCondition extends SimpleNode {
  public ASTWhenThenSearchCondition(int id) {
    super(id);
  }

  public ASTWhenThenSearchCondition(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f01e82f282f327625586b704600074ee (do not edit this line) */
