/* Generated By:JJTree: Do not edit this line. ASTWhenThenValue.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package selectParser.parser;

public class ASTWhenThenValue extends SimpleNode {
  public ASTWhenThenValue(int id) {
    super(id);
  }

  public ASTWhenThenValue(SelectParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SelectParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3c1b3d523558912d6539f169040c5ad2 (do not edit this line) */
