/* Generated By:JavaCC: Do not edit this line. SelectParserTreeConstants.java Version 4.1 */
package selectParser.parser;

public interface SelectParserTreeConstants
{
  public int JJTCOLUMN = 0;
  public int JJTVOID = 1;
  public int JJTTABLEWITHALIAS = 2;
  public int JJTTABLE = 3;
  public int JJTSELECT = 4;
  public int JJTUNION = 5;
  public int JJTPLAINSELECT = 6;
  public int JJTDISTINCT = 7;
  public int JJTSELECTITEMSLIST = 8;
  public int JJTALLCOL = 9;
  public int JJTALLTABLECOL = 10;
  public int JJTSELECTEXPRESSIONITEM = 11;
  public int JJTALLTABLECOLUMNS = 12;
  public int JJTFROMITEMSLIST = 13;
  public int JJTFROMITEM = 14;
  public int JJTJOINSLIST = 15;
  public int JJTJOINEREXPRESSION = 16;
  public int JJTWHERECLAUSE = 17;
  public int JJTGROUPBYCOLUMNREFERENCES = 18;
  public int JJTHAVING = 19;
  public int JJTORDERBYELEMENTS = 20;
  public int JJTORDERBYELEMENT = 21;
  public int JJTTOP = 22;
  public int JJTCOLUMNREFERENCE = 23;
  public int JJTCOLUMNINDEX = 24;
  public int JJTEXPRESSION = 25;
  public int JJTOR = 26;
  public int JJTAND = 27;
  public int JJTREGULARCONDITION = 28;
  public int JJTINEXPRESSION = 29;
  public int JJTBETWEEN = 30;
  public int JJTLIKEEXPRESSION = 31;
  public int JJTISNULLEXPRESSION = 32;
  public int JJTEXISTSEXPRESSION = 33;
  public int JJTSQLEXPRESSIONLIST = 34;
  public int JJTSIMPLEEXPRESSIONLIST = 35;
  public int JJTALLCOMPARISONEXPRESSION = 36;
  public int JJTANYCOMPARISONEXPRESSION = 37;
  public int JJTADD = 38;
  public int JJTMULT = 39;
  public int JJTNULL = 40;
  public int JJTJDBCPARAMETER = 41;
  public int JJTINVERSEEXPRESSION = 42;
  public int JJTDOUBLE = 43;
  public int JJTINTEGER = 44;
  public int JJTSTRING = 45;
  public int JJTUDFFUNC = 46;
  public int JJTCASEWHENEXPRESSION = 47;
  public int JJTWHENTHENSEARCHCONDITION = 48;
  public int JJTWHENTHENVALUE = 49;
  public int JJTFUNCTION = 50;
  public int JJTSUBSELECT = 51;
  public int JJTALIST = 52;
  public int JJTCOLUMNSNAMESLIST = 53;


  public String[] jjtNodeName = {
    "Column",
    "void",
    "TableWithAlias",
    "Table",
    "Select",
    "Union",
    "PlainSelect",
    "Distinct",
    "SelectItemsList",
    "AllCol",
    "AllTableCol",
    "SelectExpressionItem",
    "AllTableColumns",
    "FromItemsList",
    "FromItem",
    "JoinsList",
    "JoinerExpression",
    "WhereClause",
    "GroupByColumnReferences",
    "Having",
    "OrderByElements",
    "OrderByElement",
    "Top",
    "ColumnReference",
    "ColumnIndex",
    "Expression",
    "Or",
    "And",
    "RegularCondition",
    "InExpression",
    "Between",
    "LikeExpression",
    "IsNullExpression",
    "ExistsExpression",
    "SQLExpressionList",
    "SimpleExpressionList",
    "AllComparisonExpression",
    "AnyComparisonExpression",
    "Add",
    "Mult",
    "Null",
    "JdbcParameter",
    "InverseExpression",
    "Double",
    "Integer",
    "String",
    "UDFFunc",
    "CaseWhenExpression",
    "WhenThenSearchCondition",
    "WhenThenValue",
    "Function",
    "SubSelect",
    "AList",
    "ColumnsNamesList",
  };
}
/* JavaCC - OriginalChecksum=1fb0c830b1bd82c32138faf607e26dd3 (do not edit this line) */
