/* Generated By:JavaCC: Do not edit this line. SelectParserVisitor.java Version 4.1 */
package selectParser.parser;

public interface SelectParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTColumn node, Object data);
  public Object visit(ASTTableWithAlias node, Object data);
  public Object visit(ASTTable node, Object data);
  public Object visit(ASTSelect node, Object data);
  public Object visit(ASTUnion node, Object data);
  public Object visit(ASTPlainSelect node, Object data);
  public Object visit(ASTDistinct node, Object data);
  public Object visit(ASTSelectItemsList node, Object data);
  public Object visit(ASTAllCol node, Object data);
  public Object visit(ASTAllTableCol node, Object data);
  public Object visit(ASTSelectExpressionItem node, Object data);
  public Object visit(ASTAllTableColumns node, Object data);
  public Object visit(ASTFromItemsList node, Object data);
  public Object visit(ASTFromItem node, Object data);
  public Object visit(ASTJoinsList node, Object data);
  public Object visit(ASTJoinerExpression node, Object data);
  public Object visit(ASTWhereClause node, Object data);
  public Object visit(ASTGroupByColumnReferences node, Object data);
  public Object visit(ASTHaving node, Object data);
  public Object visit(ASTOrderByElements node, Object data);
  public Object visit(ASTOrderByElement node, Object data);
  public Object visit(ASTTop node, Object data);
  public Object visit(ASTColumnReference node, Object data);
  public Object visit(ASTColumnIndex node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTRegularCondition node, Object data);
  public Object visit(ASTInExpression node, Object data);
  public Object visit(ASTBetween node, Object data);
  public Object visit(ASTLikeExpression node, Object data);
  public Object visit(ASTIsNullExpression node, Object data);
  public Object visit(ASTExistsExpression node, Object data);
  public Object visit(ASTSQLExpressionList node, Object data);
  public Object visit(ASTSimpleExpressionList node, Object data);
  public Object visit(ASTAllComparisonExpression node, Object data);
  public Object visit(ASTAnyComparisonExpression node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTMult node, Object data);
  public Object visit(ASTNull node, Object data);
  public Object visit(ASTJdbcParameter node, Object data);
  public Object visit(ASTInverseExpression node, Object data);
  public Object visit(ASTDouble node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTString node, Object data);
  public Object visit(ASTUDFFunc node, Object data);
  public Object visit(ASTCaseWhenExpression node, Object data);
  public Object visit(ASTWhenThenSearchCondition node, Object data);
  public Object visit(ASTWhenThenValue node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTSubSelect node, Object data);
  public Object visit(ASTAList node, Object data);
  public Object visit(ASTColumnsNamesList node, Object data);
}
/* JavaCC - OriginalChecksum=e623e26ed7eb07a4e4deb78dd5b84907 (do not edit this line) */
